Populate and expose object for volcana magmaman spawning logic's data.
spelunky-fyi/overlunky pull request #320
Opened 2023-08-31 06:09 UTC by jaythebusinessgoose

2023-09-20 20:15 UTC, Dregu commented
Hmm if I add some lava in dwelling and then call spawn_effects from volcana to start the magmaman logic, it works great and the current lava tiles are added to magmaman_positions automatically, but if I start the logic first, then spawn some lava and add the MagmamanSpawnPositions manually, the game crashes when I unload the level.

2023-09-20 20:53 UTC, Dregu commented on src/game_api/state_structs.hpp
> +    std::vector<MagmamanSpawnPosition> magmaman_positions;
Yeah that works.

2023-09-23 17:29 UTC, Dregu commented
So this would also benefit from a `MagmamanSpawnPosition(x, y)` constructor that sets the timer to a random number using whatever limits and prng the game uses, or maybe even a function to create and add a spawn position to the vector and start the logic automatically in different themes.

2023-09-24 18:49 UTC, Mr-Auto requested changes

2023-09-24 18:49 UTC, Mr-Auto commented on src/game_api/state_structs.hpp
> +    virtual ~LogicMagmamanSpawn() = 0;
can you remove this virtual, it's not correct, not sure why all the logic have a separate destructor written, it's not there in the game, will change the others in my new PR

2023-09-28 19:54 UTC, Dregu commented
We don't currently have another way to start this logic anywhere, but this works

```lua
if not state.logic.magmaman_spawn then
  state.level_gen.themes[THEME.VOLCANA]:spawn_effects()
end
local x, y = math.floor(state.level_gen.spawn_x), math.floor(state.level_gen.spawn_y)
spawn_liquid(ENT_TYPE.LIQUID_LAVA, x, y)
table.insert(state.logic.magmaman_spawn.magmaman_positions, MagmamanSpawnPosition:new(x, y))
```

2023-09-28 19:56 UTC, Mr-Auto commented
Does `table.remove` also work?

2023-09-28 20:00 UTC, Dregu commented
Oh yeah or clearing the whole table to stop the spawns.

2023-09-29 19:21 UTC, merged